# Generated by Django 4.2.2 on 2025-04-06 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_is_blocked"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "permissions": [("can_block_user", "Can block user")],
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
    ]
